(defparameter *number* 0)
(defparameter *small* 0)
(defparameter *big* 102)

(defun guess-my-number ()
  (ash (+ *small* *big*) -1))

(defun smaller ()
  (setf *big* (1+ (guess-my-number)))
  (print *big*)
  (guess-my-number))

(defun bigger ()
  (setf *small* (1- (guess-my-number)))
  (print *small*)
  (guess-my-number))

(defun start-over ()
  (defparameter *small* 1)
  (defparameter *big* 100)
  (defparameter *number* 100)
  (defparameter *number* (random 100))
  (guess-my-number)
  (main))

(defun main ()
  ; (if argv
  ;   (setf *number* argv)
  (format t "Please enter a number: ")
  (setf *number* (read))
  ; )
  (print *number*)
  (loop
    (cond ((= *number* (guess-my-number))
      (print "I guesses it")
      (quit))
      ((> *number* (guess-my-number))
        (bigger))
      ((< *number* (guess-my-number))
        (smaller))
        )))
(main)
