(defparameter *number* 0)
(defparameter *small* 0)
(defparameter *big* 102)
(defparameter *mynumber* 0)

(defun guess-my-number ()
  (ash (+ *small* *big*) -1))

(defun smaller ()
  (setf *big* (1+ (guess-my-number)))
  (print *big*)
  (guess-my-number))

(defun bigger ()
  (setf *small* (1- (guess-my-number)))
  (print *small*)
  (guess-my-number))

; (defun start-over ()
;   (defparameter *small* 1)
;   (defparameter *big* 100)
;   (defparameter *number* 100)
;   (defparameter *number* (random 100))
;   (guess-my-number)
;   (main))

(defun guesser ()
  (setf *mynumber* (guess-my-number))
  (cond ((= *number* *mynumber*)
         (print "I guesses it"))
        ((> *number* *mynumber*)
         (bigger)
         (guesser))
        ((< *number* *mynumber*)
         (smaller)
         (guesser))
        ))

(defun main ()
  (print "Please enter a number: ")
  (setf *number* (read))
  ; (print *number*)
  (guesser))
