(defparameter *number* 0)
(defparameter *small* 0)
(defparameter *big* 102)
(defparameter *mynumber* 0)
(defparameter *guesses* 0)
(defparameter *again* nil)

(defun guess-my-number ()
  (ash (+ *small* *big*) -1))

(defun smaller ()
  (setf *big* (1+ (guess-my-number)))
  (setf *guesses* (1+ *guesses*))
  (guess-my-number))

(defun bigger ()
  (setf *small* (1- (guess-my-number)))
  (setf *guesses* (1+ *guesses*))
  (guess-my-number))

(defun guesser ()
  (setf *mynumber* (guess-my-number))
  (cond ((= *number* *mynumber*)
         (setf *guesses* (1+ *guesses*)))
        ((> *number* *mynumber*)
         (bigger)
         (guesser))
        ((< *number* *mynumber*)
         (smaller)
         (guesser))
        (t nil)))

(defun main ()
  (print "Please enter a number: ")
  (setf *number* (read))
  (guesser)
  (format t "~%~r tr~:@p~%" *guesses*))
